groups:
  - id: configuration
    prefix: configuration
    brief: >
      Commonly used configuration values.
    note: >
      May be used to indicate a user's explicit configuration choice, or a value
      derived from the enviroment.
    attributes:
      - id: country
        type: string
        brief: 'An ISO country code'
        note: >
          Identifies the country of the running environment using an [ISO 3166
          alpha 2](https://www.iso.org/iso-3166-country-codes.html) country code.
        examples: ['US']
      - id: language
        type: string
        brief: 'A BCP 47 language tag'
        note: >
          Identifies the preferred language of the running environment using a
          [BCP 47 language tag](https://tools.ietf.org/rfc/bcp/bcp47.txt)
        examples: ['en-US', 'zh-Hant-CN']
      - id: timezone
        type: string
        brief: 'An IANA Time Zone Database name'
        note: >
          Identifies the timezone of the running environment, using a timezone
          identifier from the IANA [Time Zone Database](https://www.iana.org/time-zones).
        examples: ['America/Los_Angeles', 'UTC']
      - id: version
        type: string
        brief: 'A configuration version'
        note: >
          An opaque configuration version identifier for systems with versioned
          configuration files. This may be a hash, semantic version, or similar
          identifying value.
        examples: ['42', '5.6.2', '808c8a73edef058f84e4b51da57c07779e48ed94']
